### ISSUE TITLE
Do we need a seperate pose2D object inside drivetrain?

### ISSUE THREAD

**Issue by FRC1787** [TheFlyingCircuits/2024-Robot#7]
Shouldn't we just use the swerveOdometry object as the single source of truth?

**Comment by CreativeName1** [comment]
The poseMeters object is used for all calls referencing the robot pose, so if we want to change the supplier of the pose from say the poseEstimator to just odometry, it would be a fast change. Otherwise, we would have to swap out every call to a pose supplier.
